Drop exit code syntax EX_* in favor of EXIT_*

diff --git a/sixarm-unix-shell-functions b/sixarm-unix-shell-functions
--- a/sixarm-unix-shell-functions
+++ b/sixarm-unix-shell-functions
@@ -20,10 +20,10 @@
 # ## Tracking
 #
 #   * Package: sixarm-unix-shell-functions
-#   * Version: 10.0.0
+#   * Version: 11.0.0
 #   * Created: 2017-08-22T00:00:00Z
-#   * Updated: 2023-01-23T19:24:54Z
-#   * License: GPL-2.0-or-later or contact us for custom license
+#   * Updated: 2023-03-16T00:48:07Z
+#   * License: GPL-2.0 or GPL-3.0 or contact us for more
 #   * Contact: Joel Parker Henderson (joel@sixarm.com)
 ##
 
@@ -144,78 +144,104 @@ ask() {
 # Exit codes
 ##
 
-# It is good practice to call exit with a value that indicates success (0) 
-# or a failure condition when ending a program. The pre-defined exit codes
+# It is good practice to call exit with a value that indicates success (0) or
+# failure (any non-0 number) when ending a program. The pre-defined exit codes
 # from sysexits can be used, so the caller of the process can get a rough
 # estimation about the failure class without looking up the source code.
 #
-# The successful exit is always indicated by a status of 0. 
+# See https://man.openbsd.org/sysexits.3
 #
-# Error numbers begin at EX__BASE to reduce the possibility of clashing with
+# Error numbers begin at EXIT__BASE to reduce the possibility of clashing with
 # other exit statuses that random programs may already return. The meaning of
 # the codes is approximately as follows.
-EX_OK=0
+#
+# The exit code list below is our preferred mix of codes from various sources:
+#
+#  * Popular conventions, such as EXIT_USAGE=2 meaning a command usage error.
+#
+#  * Our SixArm conventions, such as EXIT_CANCEL=3 meaning a user canceled.
+#
+#  * Old BSD sysexits, such as 65+, renamed from EXIT_* to EXIT_* for clarity.
+#
+# The exit code list below is subject to change over time,
+# as we learn more about Unix conventions and developer needs.
 
-# The command was used incorrectly, e.g., with the wrong number of arguments,
-# a bad flag, a bad syntax in a parameter, or whatever.
-EX_USAGE=64
+# SUCCESS e.g. the program succeeded, as defined by the program.
+# Exit 0 meaning SUCCESS is a widespread convention as a catch-all code.
+EXIT_SUCCESS=0
+
+# FAILURE e.g. the program failed, as defined by the program.
+# Exit 1 meaning FAILURE is a widespread convention as a catch-all code.
+# E.g. an error, an abort, found no results, lack of data, etc.
+EXIT_FAILURE=1
+
+# USAGE e.g. when a command is used incorrectly.
+# Exit 2 meaning USAGE is a widespread convention as a catch-all CLI code.
+# E.g. wrong number of args, a bad flag, a syntax error in an option, etc.
+# This code supersedes sysexists EXIT_USAGE=64, which is old and seldom used.
+EXIT_USAGE=2
+
+# CANCEL e.g. when a user chooses to cancel, or declines to continue, etc.
+# Exit 3 meaning CANCEL is a SixArm convention, because it's common for us.
+# E.g. a prompt says "Continue? yes/no", then the user types "n" for no.
+EXIT_CANCEL=3
 
 # The input data was incorrect in some way. This should only be used for user's
 # data and not system files.
-EX_DATAERR=65
+EXIT_DATAERR=65
 
 # An input file-- not a system file-- did not exist or was not readable.  This
 # could include errors like "No message" to a mailer-- if it cared to catch it.
-EX_NOINPUT=66
+EXIT_NOINPUT=66
 
 # The user specified did not exist. This might be used for mail addresses or
 # remote logins.
-EX_NOUSER=67
+EXIT_NOUSER=67
 
 # The host specified did not exist. This is used in mail addresses or network
 # requests.
-EX_NOHOST=68
+EXIT_NOHOST=68
 
 # A service is unavailable. This can occur if a support program or file does not
 # exist. This can also be used as a catchall message when something you wanted
 # to do does not work, but you do not know why.
-EX_UNAVAILABLE=69
+EXIT_UNAVAILABLE=69
 
 # An internal software error has been detected. This should be limited to
 # non-operating system related errors as possible.
-EX_SOFTWARE=70
+EXIT_SOFTWARE=70
 
 # An operating system error has been detected. This is intended to be used for
 # such things as "cannot fork", "cannot create pipe", or the like.  It includes
 # things like getuid returning a user that does not exist in the passwd file.
-EX_OSERR=71
+EXIT_OSERR=71
 
 # Some system file (e.g. /etc/passwd, /var/run/utx.active, etc.) does not exist,
 # cannot be opened, or has some sort of error (e.g. syntax error).
-EX_OSFILE=72
+EXIT_OSFILE=72
 
 # A user-specified output file cannot be created.
-EX_CANTCREAT=73
+EXIT_CANTCREAT=73
 
 # An error occurred while doing I/O on some file.
-EX_IOERR=74
+EXIT_IOERR=74
 
 # Temporary failure, indicating something that is not really an error.  In
 # sendmail, this means that a mailer (e.g. could not create a connection) and
 # the request should be reattempted later.
-EX_TEMPFAIL=75
+EXIT_TEMPFAIL=75
 
 # The remote system returned something that was "not possible" during a protocol
 # exchange.
-EX_PROTOCOL=76
+EXIT_PROTOCOL=76
 
 # You did not have sufficient permission to perform the operation.  This is not
-# intended for file system problems, which should use EX_NOINPUT or
-# EX_CANTCREAT, but rather for higher level permissions.
-EX_NOPERM=77
+# intended for file system problems, which should use EXIT_NOINPUT or
+# EXIT_CANTCREAT, but rather for higher level permissions.
+EXIT_NOPERM=77
 
 # Something was found in an unconfigured or misconfigured state.
-EX_CONFIG=78
+EXIT_CONFIG=78
 
 # Git bisect: The special exit code 125 should be used when the current source
 # code cannot be tested. If the script exits with this code, the current
@@ -224,13 +250,13 @@ EX_CONFIG=78
 # by POSIX shells to signal specific error status (127 is for command not found,
 # 126 is for command found but not executable—​these details do not matter, as
 # they are normal errors in the script, as far as bisect run is concerned).
-EX_GIT_BISECT_SKIP=125
+EXIT_GIT_BISECT_SKIP=125
 
 # GNU bash: If a command is found but is not executable, then return 126. 
-EX_COMMAND_FOUND_BUT_NOT_EXECUTABLE=126
+EXIT_COMMAND_FOUND_BUT_NOT_EXECUTABLE=126
 
 # GNU bash: If a command is not found, then return 127. 
-EX_COMMAND_NOT_FOUND=127
+EXIT_COMMAND_NOT_FOUND=127
 
 ##
 # Directory helpers
@@ -425,7 +451,7 @@ cmd() {
 # => exit 1
 # ```
 cmd_or_die() {
-        cmd "$1" || die "$EX_UNAVAILABLE" "Command needed: $1"
+        cmd "$1" || die "$EXIT_UNAVAILABLE" "Command needed: $1"
 }
 
 # cmd_ver_or_die: ensure a command version exists.
@@ -440,7 +466,7 @@ cmd_or_die() {
 # => exit 1
 # ```
 cmd_ver_or_die() {
-        cmd "$1" && ver "$2" "$3" || die "$EX_UNAVAILABLE" "Command version needed: $1 >= $2 (not ${3:-?})"
+        cmd "$1" && ver "$2" "$3" || die "$EXIT_UNAVAILABLE" "Command version needed: $1 >= $2 (not ${3:-?})"
 }
 
 # var: return true iff a variable exists.
@@ -469,7 +495,7 @@ var() {
 # => exit 1
 # ```
 var_or_die() {
-        var "$1" || die "$EX_CONFIG" "Variable needed: $1"
+        var "$1" || die "$EXIT_CONFIG" "Variable needed: $1"
 }
 
 # ver: return true iff a version is sufficient.
@@ -497,7 +523,7 @@ ver() {
 # STDERR=> Version needed: >= 3.3 (not 2.2)
 # ```
 ver_or_die() {
-        ver "$1" "$2" || die "$EX_CONFIG" "Version needed: >= $1 (not ${2:-?})"
+        ver "$1" "$2" || die "$EXIT_CONFIG" "Version needed: >= $1 (not ${2:-?})"
 }
 
 ##
@@ -867,7 +893,7 @@ array_i() {
                         __array_i_j=$((__array_i_j+1))
                 done
         fi
-        exit $EX_USAGE
+        exit $EXIT_USAGE
 }
 
 # array_first: return the array's first item.
@@ -1257,7 +1283,7 @@ font_exists() {
 # ```
 #
 font_exists_or_die() {
-        font_exists "$1" || die "$EX_UNAVAILABLE" "Font needed: $1" 
+        font_exists "$1" || die "$EXIT_UNAVAILABLE" "Font needed: $1" 
 }
 
 ##
